PATH="$HOME/bin:$PATH"
PAGER="less"
MANPAGER=$PAGER
EDITOR=vim
export PATH PAGER MANPAGER EDITOR

HISTFILE="$BASH/log/history"
HISTCONTROL="ignoreboth"
HISTIGNORE="ls:ll:la:l."
HISTTIMEFORMAT="%F %H:%M "
HISTSIZE="1024"
HISTFILESIZE="4096"
export HISTFILE HISTCONTROL HISTIGNORE HISTTIMEFORMAT HISTSIZE HISTFILESIZE
